name: freeze_show_shared
description: A shared Dart package for the FreezeShow backend and frontend.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.4

dependencies:
  json_annotation: ^4.9.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  build_runner: ^2.3.3
  json_serializable: ^6.8.0
