name: freeze_show
description: TV information - easy and beautiful

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  get_it: ^7.2.0 # Dependency Injector
  flutter_bloc: ^8.1.6 # State manager
  dio: ^5.7.0 # Http handler
  dartz: ^0.10.1 # Tools to simplify dart data
  rxdart: ^0.28.0 # Reactive functions
  google_fonts: ^6.2.1 # Fonts
  flutter_html: ^2.2.1 # Html parser

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/app-icon.png
    - assets/film-poster-placeholder1.png
